import './components/swiper';
import './components/tabs';
import './components/acardion';
import './components/modal';
import './components/job';
import './components/calculator';
import './components/smooth-scroll';
import './components/burger';
import './components/validate';
